version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.1

workflows:
  test-deploy-post-deploy:
    jobs:
      - post-deploy:
          steps:
            - checkout
            - lighthouse-check/audit:
                configFile: "./lighthouse-check.json"
                awsAccessKeyId: $AWS_ACCESS_KEY_ID
                awsBucket: $AWS_BUCKET
                awsRegion: $AWS_REGION
                awsSecretAccessKey: $AWS_SECRET_ACCESS_KEY
                slackWebhookUrl: $SLACK_WEBHOOK_URL
          filters:
            branches:
              only: master
