version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  post-deploy:
    docker:
      - image: circleci/buildpack-deps:jessie-curl
    steps:
      - run:
          name: Run a performance audit
          command: |
            curl -X POST "https://www.foo.software/api/v1/queue/items" --insecure \
              -H "accept: application/json" -H "Content-Type: application/json" \
              -d "{ \"pages\": \"$FOO_PAGE_TOKENS\", \"tag\": \"Build %23 $CIRCLE_BUILD_NUM\" }"

workflows:
  version: 2
  test-deploy-post-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - post-deploy:
          requires:
            - deploy
