version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.1

jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  post-deploy: 
    executor: lighthouse-check/default
    steps:
      - checkout
      - lighthouse-check/audit:
          configFile: "./lighthouse-check.json"
          awsAccessKeyId: $AWS_ACCESS_KEY_ID
          awsBucket: $AWS_BUCKET
          awsRegion: $AWS_REGION
          awsSecretAccessKey: $AWS_SECRET_ACCESS_KEY
          slackWebhookUrl: $SLACK_WEBHOOK_URL

workflows:
  test-deploy-post-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - post-deploy:
          requires:
            - deploy
