version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  post-deploy:
    docker:
      - image: foosoftware/lighthouse-check-cli:latest
    steps:
      - checkout
      - run:
          name: Run a performance audit
          command: |
            lighthouse-check --apiToken $LIGHTHOUSE_CHECK_API_TOKEN --urls $LIGHTHOUSE_CHECK_URLS

workflows:
  version: 2
  test-deploy-post-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - post-deploy:
          requires:
            - deploy
